global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Streamlit metrics (predictions via UI)
  - job_name: 'heart-disease-streamlit'
    static_configs:
      #- targets: ['heart-disease-streamlit-service:8001']
      - targets: ['streamlit:8001'] # work with docker compose
    metrics_path: /metrics