apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-streamlit
  labels:
    app: heart-disease-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-streamlit
  template:
    metadata:
      labels:
        app: heart-disease-streamlit
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/"
    spec:
      containers:
        - name: streamlit
          image: ishranaznin/heart-disease-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501   # Streamlit UI
            - containerPort: 8001   # Prometheus metrics
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "510m"
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 15