apiVersion: v1
kind: Service
metadata:
  name: heart-disease-streamlit-service
  labels:
    app: heart-disease-streamlit
spec:
  type: NodePort
  selector:
    app: heart-disease-streamlit
  ports:
    - name: streamlit-ui
      protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30081          # access via minikube-ip:30081

    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30082 